#!/bin/sh
#Визначити свою IP-адресута маску підмережі
ip a

#Визначити IP-адресу шлюзу за замовчанням(default gateway)
ip route show default

#Визначити IP-адресу вузла google.com.ua
nslookup google.com

#Визначити ім’я вузла з IP-адресою 8.8.8.8
nslookup 8.8.8.8

#Перевірити, чи доступний по мережі 127.0.0.1
ping -c 4 127.0.0.1

#Знайти перші 3 маршрутизатори на шляху до вузла google.com
traceroute -m 3 google.com

#Визначитиім’я вузла з IP-адресою 77.47.133.222
nslookup 77.47.133.222

